hoodie/notify-rust

examples/signal_listener.rs, examples/update.rs, examples/wait_for_closing.rs, src/lib.rs, tests/lib.rs
I moved functionality for displayed notifications to NotificationHandle.
The old way of doing things was removed since it allowed to mess up things too easily.
Affected is notably the way you `close`, `wait_for_action` and `update` ([see how the examples change](https://github.com/panicbit/notify-rust/commit/37f93b742dd694c47a37e5b960fe32beb9f68ef9)).
=> Revise API [breaking change]

Cargo.toml, src/lib.rs
Hi.
Please don't hardcode "linux" when you mean "any UNIX-like OS" ;-)
With this change and diwic/dbus-rs#36, all tests pass on FreeBSD.
=> Use cfg(unix) instead of linux

src/hints.rs, src/util.rs
When you want to display a volume bar you need a hint with an `int` value. So this PR adds a `CustomInt` variant to the `NotificationHint` enum.
=> added custom int option

src/lib.rs
I can't find the `Error` that's returned from some of the functions like `Notification`'s `show` functions.
=> exposed dbus Error because its returned in public methods

Cargo.toml, examples/countdown.rs, examples/images.rs, examples/info.rs, examples/on_close.rs, examples/server.rs, examples/sound.rs, examples/update.rs, examples/windows.rs, src/error.rs, src/lib.rs, tests/realworld.rs
Work towards resolving #37
This adds text and sound (as much as windows toasts can have sound) notifications for windows.
The changes to the tests might break tests on macos, not sure.
Images and icons are not exposed. Hints might be a good way to do that.
=> More windows support progress

README.md
The documentation missed the compiletime requirement `libdbus-1-dev`.
When using this crate without having `libdbus-1-dev` installed, `cargo build` fails with the following error message on a linux system:
```
error: failed to run custom build command for `dbus v0.4.1`
process didn't exit successfully: `[…]target/debug/build/dbus-17d90d6172f41386/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1\"` did not exit successfully: exit code: 1\n--- stderr\nPackage dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n"', libcore/result.rs:945:5 …
```
=> Complement requirements documentation and examples

Cargo.toml, src/hints.rs
fixed compilation error for iamges example with debian
```   Compiling notify-rust v3.6.2 (/home/*/Dokumente/Rust/notify-rust)
error[E0464]: multiple matching crates for `lazy_static`
--> src/lib.rs:163:1
|
163 | extern crate lazy_static;
| ^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: candidates:
crate `lazy_static`: /home/*/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblazy_static-d66edcc18da7b065.rlib
crate `lazy_static`: /home/*rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblazy_static-c786832e7e103fc8.rlib
error[E0463]: can't find crate for `lazy_static`
--> src/lib.rs:163:1
|
163 | extern crate lazy_static;
| ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
error: aborting due to 2 previous errors
For …
```
=> images features now depends on lazy_static

src/image.rs
Image struct has the field `alpha`, but no actual method to convert any images with alpha.
This PR does:
- Add `from_rgba` method to convert images with alpha
- Implement `TryFrom` trait for `image::RgbImage` and `image::RgbaImage`
- Fix `TryFrom` trait implementation for `image::DynamicImage` able to convert `DynamicImage::ImageRgba8`
=> Implement converting images with alpha

src/macos.rs, src/notification.rs
Hi, I've added scheduling support for macos. This feature is already present in the [mac-notification-sys](https://github.com/h4llow3En/mac-notification-sys/blob/2ee92b82478448f45f0c573e8852ea9ad9377d2d/src/notification.rs#L112) library.
Thought it was best not to add it as an attribute of `Notification` since this is only intended for macos, and that would've meant a far greater change that was not worth it in my opinion. Also since the `schedule` method receives a `f64` input, it adds legibility.
Tell me what you think, and if I have to make changes.
Cheers!
~Edit: Just seen the commit guidelines, will update pr.~
=> Add schedule support for macos notification

.github/workflows/ci.yml, Cargo.toml, examples/mac.rs, examples/schedule.rs, src/hints.rs, src/notification.rs, src/timeout.rs
Hi @guillermoap,
I found the `Notification::schedule(delivery_date: f64)` to be a bit raw. So I took the liberty to rename it to `Notification::schedule_raw(timestamp: 64)` and added `Notification::schedule(dalivery_date: chrono:: DateTime)` instead.
check out https://github.com/hoodie/notify-rust/blob/feature/hendriks/schedule-raw/examples/schedule.rs
what do you think?
=> feat: add schedule_raw() for f64 timestamps

.github/workflows/ci.yml
It also disables it for branches other than main, as that avoids double-builds when they've also got a PR
=> Enables CI on PRs

.gitignore, examples/mac_app_id.rs, src/error.rs, src/lib.rs, src/macos.rs
Addressing #138, seems we accidentally reexported the wrong types on macos, but not the ones we need.
=> fix: re-exported types from mac-notification-sys

Cargo.toml
This PR updates the `winrt-notification` dependency to use [tauri-winrt-notification](https://github.com/tauri-apps/winrt-notification), a fork we will maintain until the original author is able to fix a security [vulnerability](https://rustsec.org/advisories/RUSTSEC-2022-0008.html) that exists because of an outdated windows version.
This fork updates the windows dependency to 0.39.0, which requires Rust 1.59.0. Other operating systems are not affected by it so that's why I kept the original MSRV in the Cargo manifest.
=> feat: update winrt-notification to a maintained fork, closes #148

README.md
zbus is a pure Rust library so `-rs` suffice is neither used nor necessary. :)
=> docs: Fix a few typos w/ crate names

src/timeout.rs, src/xdg/mod.rs
Useful when wanting to pass it as a command line argument to an application.
I recently needed to pass the notification timeout on the command line. I ended up implementing a custom function, but thought maybe it would be a nice addition:
See https://github.com/rnestler/reboot-arch-btw/pull/106/files#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR18-R25
If you think this is a good thing, then I'd of course also add tests and whatever else you think is necessary.
=> Implement FromStr for Timeout

src/timeout.rs, tests/realworld.rs
See [this discussion](https://github.com/hoodie/notify-rust/discussions/171).
=> feat: Accept durations as timeout arguments

.github/workflows/ci.yml, Cargo.toml
On macOS we would always show a redundant "Show" button, this is now fixed in https://github.com/h4llow3En/mac-notification-sys/releases/tag/v0.6.0
=> fix: remove redundant action button on macOS

Cargo.toml
[This feature allows static linking][1].
[1]: https://github.com/diwic/dbus-rs/blob/master/libdbus-sys/cross_compile.md
=> Add feature `d_vendored` to enable dbus/vendored feature

src/timeout.rs
Explicitly cast `as_millis()` result to `u128` to avoid type inference error. This fixes compilation failure in `notify-rust` related to `PartialOrd` trait ambiguity when comparing `duration.as_millis()` with `u32::MAX.into()`.
Refs: rust-lang/rust#E0283
=> fix: resolve type inference issue with u32::MAX conversion

Cargo.toml
To make build `notify-rust` without `async-io` as optional
=> feat: add `z-with-tokio` feature
